DROP TABLE IF EXISTS categories, users, compilations_events, events, compilations, participation_requests, rating_events;

CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(100) NOT NULL,
  CONSTRAINT pk_category PRIMARY KEY (id),
  CONSTRAINT uq_category_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  annotation VARCHAR(2000) NOT NULL,
  category_id BIGINT NOT NULL,
  created_on TIMESTAMP WITHOUT TIME ZONE,
  description VARCHAR(7000) NOT NULL,
  event_date TIMESTAMP WITHOUT TIME ZONE,
  initiator_id BIGINT NOT NULL,
  lat DECIMAL(8,6) NOT NULL,
  lon DECIMAL(9,6) NOT NULL,
  paid BOOLEAN DEFAULT false,
  participant_limit BIGINT,
  published_on TIMESTAMP WITHOUT TIME ZONE,
  request_moderation BOOLEAN DEFAULT true,
  state VARCHAR(20) NOT NULL,
  title VARCHAR(120) NOT NULL,
  CONSTRAINT pk_event PRIMARY KEY (id),
  CONSTRAINT fk_event_for_category FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE TABLE IF NOT EXISTS compilations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  pinned BOOLEAN,
  title VARCHAR(255) NOT NULL,
  CONSTRAINT pk_compilation PRIMARY KEY (id),
  CONSTRAINT uq_compilation_title UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS compilations_events (
  compilation_id BIGINT NOT NULL,
  event_id BIGINT NOT NULL,
  CONSTRAINT pk_compilations_events primary key (compilation_id, event_id),
  CONSTRAINT fk_comeve_on_compilation foreign key (compilation_id) references compilations (id),
  CONSTRAINT fk_comeve_on_event foreign key (event_id) references events (id)
);

CREATE TABLE IF NOT EXISTS participation_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created TIMESTAMP WITHOUT TIME ZONE,
  event_id BIGINT NOT NULL,
  requester_id BIGINT NOT NULL,
  state VARCHAR(20) NOT NULL,
  CONSTRAINT pk_participation_request PRIMARY KEY (id),
  CONSTRAINT fk_participation_request_for_event FOREIGN KEY (event_id) REFERENCES events (id),
  CONSTRAINT fk_participation_request_for_user FOREIGN KEY (requester_id) REFERENCES users (id),
  CONSTRAINT uq_participation_requests_for_event_id_requester_id UNIQUE (event_id, requester_id)
);

CREATE TABLE IF NOT EXISTS rating_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  event_id BIGINT NOT NULL,
  appraiser_id BIGINT NOT NULL,
  state VARCHAR(7) NOT NULL,
  CONSTRAINT pk_rating_events PRIMARY KEY (id),
  CONSTRAINT uq_rating_events_for_event_id_appraiser_id UNIQUE (event_id, appraiser_id)
);


