version: '3.1'
services:
  stats-server:
    build: ./stats-server/server/
    #image: stats-server
    #tty: true
    container_name: stats-server
    ports:
      - "9090:9090"
     # - "9091:9091"
    depends_on:
      - stats-db
     # - ewm-service
    environment:
      - DB_HOST=stats-db
      - DB_PORT=5432
      - DB_NAME=stats-server
      - DB_USER=postgres
      - DB_PASSWORD=root
      #- ewm-service_SERVER_URL=http://server:8080
      #- SPRING_PROFILES_ACTIVE=default

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ewm-service/
    #image: ewm-service
    #tty: true
    container_name: ewm-service
    ports:
      - "8080:8080"
      #- "8081:8081"
    depends_on:
      - ewm-db
      #- stats-server
    environment:
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - DB_NAME=ewm-service
      - DB_USER=postgres
      - DB_PASSWORD=root

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root